syntax/ruby.vim
These have made it into the community style guide here:
https://github.com/bbatsov/ruby-style-guide#comment-annotations
So it would be great to add highlighting for these.
=> Add HACK and REVIEW as comment annotations

syntax/ruby.vim
Current syntax highlight treats if statement modifiers as if blocks, if they are written after a line continuation backslash.  For example:
do_something(args) \
if condition
The above would incorrectly expect an "end" statement.
This change modifies rubyConditionalExpression region to ignore "if" that is following a line continuation character.  Then rubyConditionalModifier will correctly highlight just the "if" keyword.
=> Allow statement modifiers after line continuation

ftplugin/ruby.vim
For certain files invoking :Gdiff caused error - could not read file
.ruby-version in .git directory. Now it checks if the file is readable before
trying to read it.
=> Fix issue with opening fugitive diff

ftdetect/ruby.vim
`Routefile` is the standard file for [Roadworker](https://github.com/winebarrel/roadworker). Roadworker is a tool to manage Route53. It defines the state of Route53 using DSL, and updates Route53 according to DSL.
It would be great to have this in vim-ruby.
=> Add syntax detection for Routefile

syntax/ruby.vim
`.?`, the "safe navigation operator", [has been accepted into Ruby](https://github.com/ruby/ruby/commit/a356fe1c3550892902103f66928426ac8279e072) and
presently conflicts with the rule for highlighting `?c` character
literals. This patch remedies the issue by adding `\.` to the class of
preceding characters which refute such a match.
I refrained from adding `.?` to `rubyOperator` only for symmetry with
the absence of `.` therein, but `.?` is sufficiently "weird" as to be
worth considering making an exception for; it's the sort of thing that
really ought to stand out, in my estimation.
That `::` can be used for method invocation seems to have been largely
forgotten, but I suspect `::?` will eventually find its way in, at which
time another patch very much like this one will be necessitated.
=> Don't highlight `.?c` as a "character" literal.

syntax/ruby.vim
In short, the following program is valid (as of 1.9) and should be highlighted appropriately.
```ruby
def +@; end
def -@; end
def !@; end
def ~@; end
send :+@
send :-@
send :!@
send :~@
```
=> Highlight all of the unary methods.

syntax/ruby.vim
#274 and #279 were a little hasty. [The safe navigation operator has been changed from `.?` to `&.`.](https://github.com/ruby/ruby/commit/837babd56459aafc1232a12fbfa783025d619b98) This patch undoes those and only matches the second ampersand in `4&.&2` as `rubyOperator`.
=> Account for new safe navigation operator

compiler/rspec.vim
RSpec 3.4 introduced a small change to its failure messages. Given the following spec file:
```ruby
RSpec.describe "blah" do
it "definitely does not raise hell" do
raise "hell"
end
end
```
RSpec 3.3 outputs:
blah
definitely does not raise hell (FAILED - 1)
Failures:
1) blah definitely does not raise hell
Failure/Error: raise "hell"
RuntimeError:
hell
<snip>
RSpec 3.4 outputs:
blah
definitely does not raise hell (FAILED - 1)
Failures:
1) blah definitely does not raise hell
Failure/Error: raise "hell"
RuntimeError:
hell
<snip>
This change adds a multi-line continuation rule to the RSpec compiler allowing it to ignore empty lines in multi-line error messages.
In dispatch.vim this is the difference between this:
...and this:
---
Edit: FWIW I wondered whether this might be a bug in RSpec, but …
=> Add support for RSpec 3.4 to compiler

spec/indent/basic_spec.rb, syntax/ruby.vim
I saw that vim-ruby doesn't support for [Ruby 2.3 <<~ heredoc syntax](https://bugs.ruby-lang.org/issues/9098) yet. I'm not sure if my patch covers all the cases, but I decided to submit a working PR instead of just opening an empty issue.
The patch itself is basically a copy-paste of the previous for `syn` lines with `<<\~` substituted for `<<-`. I took <<- spec and adapted it for <<~.
=> Add support for Ruby 2.3 heredoc <<~ syntax

indent/ruby.vim, spec/indent/blocks_spec.rb
All of the tests pass. It simplifies matching blocks a lot. And it fixes indenting blocks with arguments that have default values.
=> Match much more complicated structures in block's arguments in a very simple way.

CONTRIBUTORS, doc/vim-ruby.txt, indent/ruby.vim, spec/indent/blocks_spec.rb
Allow blocks to be indented based on the `do` line by setting the
`g:ruby_indent_block_style` to `do` instead of the current default of
`expression`.
When this variable is set to `do` the following are acceptable
indentaions:
line_one do |x|
something
end
line_one
.line_two do |x|
something
end
When this variable is set to `expression` the following are acceptable
indentations:
line_one do |x|
something
end
line_one
.line_two do |x|
something
end
P.S: I think the `do` style is a more reasonable default, but it is not backwards-compatible. I don't know how you feel about that, but please let me know if you would like the default changed.
=> Add configurable block style indentation

ftplugin/ruby.vim
I have custom am, im, aM and iM mappings in my configuration.
However, the ftplugin is doing the wrong check when overriding the checks. This pull request fixes that.
=> Fix maparg check for am, im, aM and iM mappings

ftplugin/ruby.vim
https://github.com/vim-ruby/vim-ruby/issues/300
Including RubyGems libraries in finding the Ruby's default
load path is not necessary and it causes slow operation.
* Use --disable-gems flag to make the operation fast
=> Exclude rubygems in finding the default load path

syntax/ruby.vim
For example:
```ruby
[1,2,3].each do
|x|
end
```
See https://github.com/rubyzip/rubyzip/issues/236#issuecomment-126581538
=> Block parameters are possible to be in next line.

indent/eruby.vim, spec/indent/eruby_spec.rb, spec/spec_helper.rb
Consider this template:
```eruby
<form>
<div>
<%= text_field_tag :email, nil,
placeholder: "email" %>
</div>
</form>
```
Currently, reindenting whole file produces:
```eruby
<form>
<div>
<%= text_field_tag :email, nil,
placeholder: "email" %>
</div>
</form>
```
note the closing div tag.
I'm not very familiar with vimscript, so maybe there is a better approach to detecting this situation.
=> fix indent for closing html tag after multiline erb tag

indent/ruby.vim, spec/indent/continuations_spec.rb
With `let g:ruby_indent_end_alignment = "hanging"`
```ruby
x = if condition
something
end
```
vs
With `let g:ruby_indent_end_alignment = "variable"`
```ruby
x = if condition
something
end
```
See https://github.com/bbatsov/rubocop/blob/dd94c4d867cc57e13d70537953e06165b19d168f/config/default.yml#L1287
=> Add option for end alignment of variable assignments

autoload/rubycomplete.vim
`neovim-ruby` does not support multi-threaded RPC requests, so
attempting to spawn a thread crashes the provider process (see
https://github.com/alexgenco/neovim-ruby/issues/28).
I also fixed a typo `require 'Thread'` -> `require 'thread'`
(lowercase). I'm not sure how this code could have actually worked,
since `require 'Thread'` raises a `LoadError`. If this error is getting
swallowed by the `rescue`, I would probably prefer we just get rid of
the threading logic completely, as I'm not clear what its purpose is.
=> Skip spawning thread in nvim

syntax/ruby.vim
Suppose we have a class & module declaration:
```ruby
class A
end
module B
end
```
Without this patch, `A` and `B` will be highlighted as `rubyConstant`.
After this patch, they will be highlighted as `rubyClassDeclaration` and `rubyModuleDeclaration` respectively.
=> Allow custom highlighting on class/module declaration

syntax/ruby.vim
Submitting this as a PR because I'm changing a very longstanding default and want to make sure everyone is in the loop and on board. I feel like class level DSL makes much more sense as `Define` than `Statement`. `attr_accessor` and friends are literally just wrappers around `def`. Plus, `Statement` is used for a huge percentage of things; this change balances things out a bit.
=> Highlight class level DSL as Define

ftplugin/ruby.vim
I noticed that `a:0` was always `0` (and `a:1` was never defined).
=> Remove deadcode

syntax/ruby.vim
`end` and `endif` are equal in Vim script.
https://github.com/vim/vim/blob/833093bfb0e4a7f89b5adc66babcfa8ac09cfda9/runtime/doc/eval.txt#L10007
I think it is confusing that is using `end` instead of `endif`. And vim-ruby uses `endif` in other places. So it should be `endif`.
=> Replace `if` - `end` with `if` - `endif`

compiler/rspec.vim
Previously we only recognized failures directly followed by a message
like so:
```
Failure/Error: expect(response).to redirect_to(store)
```
With this update we also recognize failures where the message is on the
next line like so:
```
Failure/Error:
expect {
put :update, params: update_params(engineer_role)
}.to change { user.reload.role }.to(engineer_role)
```
This is my first time working with vim's `CompilerSet` format. From what i can read it's not possible to make it any more dry by making the `%m` on the existing format optional. So this was the best solution i could figure out.
=> Support failure without a message on the same line in rspec compiler

indent/ruby.vim
There’s nothing special about `public`/`protected`/`private` (which were previously hard-coded), and any valid method name should be permitted.
Methods with non-letter characters won't work (e.g. `∞`), because a complete regular expression for a Ruby method name is complicated. Non-ASCII characters (e.g. `ñ`) will work.
I can’t think of any edge cases which this would break. I thought many single-line `def`s may (e.g. `def f; end; def g; end`), but as they must be separated by a `;`, it still works okay.
One note is that [vim-endwise](https://github.com/tpope/vim-endwise) should probably get a matching update as well.
Fixes #370.
=> Change indentation to allow (almost) any method call to precede a `def` call

indent/ruby.vim
Hello! Today I've updated my vim plugins and noticed that there had been an error introduced in [one of the latest commits](https://github.com/vim-ruby/vim-ruby/commit/eec4d8957df77220632f040fecc3c42e11ff7bdd#diff-bca3ba1cf5f64360a6ba030a95a6e902R61).
After the fix the plugin seems to be working OK. :grin:
Thanks for maintaining this project and have a nice day!
Stay awesome! 😎
=> Fix missing comma in `indent/ruby.vim` in `s:syng_strcom` list

ftdetect/ruby_extra.vim
The Sorbet type checker allows writing "Ruby Interface" files in order to learn Sorbet about what classes are defined and what are interfaces of the methods. The RBI files are pure Ruby files by [definition](https://sorbet.org/docs/rbi#syntax). Hence, it would be nice to set the filetype to `ruby` automatically once the RBI file is opened.
=> Automatically detect Sorbet RBI files as Ruby files

ftplugin/ruby.vim
Noticed this with `env -u HOME vim …`, where `exe 'cd'` with an empty
string then would fail (due to missing `$HOME` also).
https://github.com/vim/vim/blob/7306d6/runtime/ftplugin/ruby.vim#L79
=> Handle empty `$HOME` in ftplugin

spec/syntax/maxmempattern_limit_spec.rb, syntax/ruby.vim
This particular pattern matches symbols in hashes and block argument lists (it seems), so that's the places we'll say it's contained.
More explanations in: https://github.com/vim-ruby/vim-ruby/issues/412
=> Try fixing a memory-intensive pattern

doc/ft-ruby-indent.txt, indent/ruby.vim, spec/indent/blocks_spec.rb, spec/indent/continuations_spec.rb, spec/indent/hanging_elements_spec.rb, spec/indent/indent_access_modifier_spec.rb, spec/indent/nesting_spec.rb, spec/indent/splat_spec.rb, spec/spec_helper.rb
The executive summary is that this PR adds a global setting to indent like this:
```
render('product/show',
product: product,
on_sale: true,
)
```
The PR includes documentation and tests. The whole test suite still passes. With the default value, it should not affect current indenting behaviour at all.
The first commit is a small refactoring of the indentation specs. Half of these were failing when run as individual files, because they relied upon global state being modified in other files. I just made it so every test starts with the globals set to their default value, automatically.
I tried to stick to the conventions I found in the project, but I'm open to making changes.
=> Add option to avoid hanging indents

spec/syntax/symbols_spec.rb, spec/vim/plugin/syntax_test.vim, syntax/ruby.vim
There's a syntax bug with nested parentheses in symbols. Here's an example:
``` ruby
h = %i(
foo(bar)baz
)
```
The closing bracket after `bar` is actually highlighted as `rubyString` while everything else inside `%i(` is a `rubySymbol`. 
It seems like one way to solve this is to just remove the `matchgroup=rubyString`. From what I understand, the only reason the nested groups exist is to ensure that closing brackets are not confused, but we should be able to leave them "transparent" for the syntax engine.
Would appreciate a review by @dkearns in particular for the test tweak.
=> Nested parens in symbols

ftdetect/ruby_extra.vim
https://github.com/amatsuda/jb
Jb is an alternative to Jbuilder, a template library that generates JSON from pure Ruby code.
=> Add Jb template file detection

spec/syntax/comments_spec.rb, syntax/ruby.vim
Ruby 3.0.0 added a new magic comment for making different literals
"shareable" (a.k.a frozen).
Here is a link to the docs: https://github.com/ruby/ruby/blob/cfbf2bde4002821d12047b2aba0010739aaf925e/doc/syntax/comments.rdoc#label-shareable_constant_value+Directive
Here's a demo of the feature:
```
$ cat test.rb
FOO = [ 1, 2, 3 ]
p FOO.frozen?
$ ruby test.rb
true
```
=> Add highlighting for shareable_constant_value

indent/ruby.vim
Make the `in` keyword within a `case` pattern-matching statement remove
a level of indentation, similar to `when`.
Before:
```ruby
case {a: a}
in {a:}
p a
end
```
After:
```ruby
case {a: a}
in {a:}
p a
end
```
Fixes https://github.com/vim-ruby/vim-ruby/issues/444
=> Fix indentation for `in` keyword

indent/ruby.vim, spec/indent/case_in_spec.rb, spec/spec_helper.rb
Since de3d94917942496d3782e564b3779a2600b18a15, the `in` keyword is properly de-indented, but I find it very annoying when typing anything starting with `in` but not in the context of a `case` statement, most often with a variable called `index`.
Technically we could do something similar for `elsif`, `when`, but I rarely encounter the same issue with those so I'm not sure it's worth changing.
=> Wait for space after `in` to indent in insert mode

autoload/rubycomplete.vim
Hello!
Just a quick fix on the Ruby code.
`File.exists?` was removed on Ruby 3.2.0:
* https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
* https://bugs.ruby-lang.org/issues/17391
So if you `let g:rubycomplete_rails=1` and `C-X C-O`
```
Error detected while processing function rubycomplete#Complete[22]..provider#ruby#Call[17]..rubycomplete#Complete:
line   22:
NoMethodError: undefined method `exists?' for File:Class
```
The PR just uses `File.exist?` instead. Method does the same and has been present at least since Ruby 1.8.6:
* https://ruby-doc.org/core-1.8.6/File.html#method-c-exist-3F
=> Stop using deprecated File.exists?
